# Generated by Django 4.1.2 on 2023-01-12 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlockCommonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContentBlockContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='QACommonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downvoted_by', models.ManyToManyField(blank=True, related_name='downvoted_by', to='user.usercommoninfo')),
                ('upvoted_by', models.ManyToManyField(blank=True, related_name='upvoted_by', to='user.usercommoninfo')),
            ],
        ),
        migrations.CreateModel(
            name='QALibQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('asked_on', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('asked_by', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='user.student')),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='qalib.qacommoninfo')),
                ('question_details', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='qalib.contentblockcontainer')),
            ],
        ),
        migrations.CreateModel(
            name='QALibTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='qalib.contentblockcommoninfo')),
            ],
        ),
        migrations.CreateModel(
            name='QALibQuestionView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_on', models.DateTimeField(auto_now_add=True)),
                ('viewed_by', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='user.usercommoninfo')),
                ('viewed_question', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='views', to='qalib.qalibquestion')),
            ],
        ),
        migrations.AddField(
            model_name='qalibquestion',
            name='tags',
            field=models.ManyToManyField(to='qalib.qalibtag'),
        ),
        migrations.CreateModel(
            name='QALibAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_on', models.DateTimeField(auto_now_add=True)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='qalib.contentblockcontainer')),
                ('answered_by', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='user.teacher')),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='qalib.qacommoninfo')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='answers', to='qalib.qalibquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ImageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='QALib')),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='qalib.contentblockcommoninfo')),
            ],
        ),
        migrations.AddField(
            model_name='contentblockcommoninfo',
            name='content_container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='qalib.contentblockcontainer'),
        ),
    ]
