# Generated by Django 4.1.2 on 2023-01-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('qalib', '0002_alter_qalibquestion_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qacommoninfo',
            name='downvoted_by',
        ),
        migrations.RemoveField(
            model_name='qacommoninfo',
            name='upvoted_by',
        ),
        migrations.AddField(
            model_name='qacommoninfo',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='downvotes', to='user.usercommoninfo'),
        ),
        migrations.AddField(
            model_name='qacommoninfo',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvotes', to='user.usercommoninfo'),
        ),
    ]
