# Generated by Django 4.1.2 on 2023-01-12 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qalib', '0003_remove_qacommoninfo_downvoted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblockcommoninfo',
            name='type',
            field=models.CharField(choices=[('T', 'Text'), ('I', 'Image')], default=2, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contentblockcommoninfo',
            name='content_container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='blocks', to='qalib.contentblockcontainer'),
        ),
    ]
