# Generated by Django 4.1.2 on 2023-01-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qalib', '0004_contentblockcommoninfo_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblockcommoninfo',
            name='type',
            field=models.CharField(choices=[('txt', 'Text'), ('img', 'Image')], max_length=3),
        ),
    ]
