# Generated by Django 4.1.2 on 2023-01-25 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qalib', '0005_alter_contentblockcommoninfo_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qalibanswer',
            old_name='answer',
            new_name='answer_block',
        ),
        migrations.AlterUniqueTogether(
            name='contentblockcommoninfo',
            unique_together={('content_container', 'ordering')},
        ),
    ]
