# Generated by Django 4.1.2 on 2023-01-25 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qalib', '0006_rename_answer_qalibanswer_answer_block_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QALibTag',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='qalibquestion',
            old_name='question_details',
            new_name='question_details_block',
        ),
    ]
