# Generated by Django 4.1.2 on 2023-02-07 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qalib', '0007_rename_qalibtag_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageblock',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='qalib.contentblockcommoninfo'),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='qalib.contentblockcommoninfo'),
        ),
    ]
