# Generated by Django 4.1.2 on 2023-02-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('qalib', '0008_alter_imageblock_info_alter_textblock_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qacommoninfo',
            name='downvotes',
            field=models.ManyToManyField(blank=True, default=0, related_name='downvotes', to='user.usercommoninfo'),
        ),
        migrations.AlterField(
            model_name='qacommoninfo',
            name='upvotes',
            field=models.ManyToManyField(blank=True, default=0, related_name='upvotes', to='user.usercommoninfo'),
        ),
    ]
