# Generated by Django 4.1.2 on 2023-02-11 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('qalib', '0009_alter_qacommoninfo_downvotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qalibanswer',
            name='answered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='answered_questions', to='user.teacher'),
        ),
    ]
