# Generated by Django 4.1.2 on 2023-04-16 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('learning_resources', '0002_alter_qfgrading_correct_answer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qfmcquestionresponse',
            unique_together={('responder', 'responding_question')},
        ),
    ]
