# Generated by Django 4.1.2 on 2023-04-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_resources', '0003_alter_qfmcquestionresponse_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciselearningresource',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
