# Generated by Django 4.1.2 on 2023-04-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_resources', '0004_exerciselearningresource_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciselearningresource',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
