# Generated by Django 4.1.2 on 2023-04-16 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_resources', '0005_alter_exerciselearningresource_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonexerciselearningresource',
            name='related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='learning_resources.nonexerciselearningresource'),
        ),
    ]
