# Generated by Django 4.1.2 on 2023-04-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_resources', '0006_nonexerciselearningresource_related'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonexerciselearningresource',
            name='related',
        ),
        migrations.AddField(
            model_name='nonexerciselearningresource',
            name='related_to',
            field=models.ManyToManyField(related_name='related', to='learning_resources.nonexerciselearningresource'),
        ),
    ]
