# Generated by Django 4.1.2 on 2023-04-23 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_resources', '0013_remove_exerciselearningresource_related_exercises_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qfmcquestionoption',
            name='belong_to_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='learning_resources.qfmcquestion'),
        ),
    ]
